### ISSUE TITLE
Other SageAttention Kenerls

### ISSUE THREAD

**Issue by Andy0422** [thu-ml/SageAttention#16]
Do you have a plan to release other quantized P,V kernels? and a framework to employ the adaptive kernel selection is also well welcome.

**Comment by jt-zhang** [comment]
These functions will be available soon in the next release.

**Comment by jason-huang03** [comment]
Check branch 2.0.0 for preview now! We now quantize P, V to fp8.

**Comment by Vezora-Corp** [comment]
@jason-huang03 will there be backward pass kernels in the future? This would be absolutely killer!

**Comment by jason-huang03** [comment]
@Vezora-Corp Doing quantization in backwarp pass poses greater challenges than forward pass. Our next step is to write kernel on H100/H800 that matches performance of flash attention 3. After that, I think we will try to see whether it is possible to extend sage attention to backward pass. I think backward pass will be most useful on Hopper GPUs where large scale pretraining are done, so we will first write the forward pass kernel on Hopper.

**Comment by Vezora-Corp** [comment]
@jason-huang03 sad (as a 3090 cluster owner), but totally understandable. Thank you!

**Comment by jt-zhang** [comment]
Hi. For **trainable** efficient attention, I recommend [https://github.com/thu-ml/SLA](https://github.com/thu-ml/SLA) currently.
