### ISSUE TITLE
Would support other headdim

### ISSUE THREAD

**Issue by v4if** [thu-ml/SageAttention#17]
Would support other headdim? Like 512.

**Comment by jason-huang03** [comment]
In the upcoming release, we will include kernels for head dimension of 256. However, models with a head dimension of 256 are already quite rare (only gemma-2 2b/9b as far as I know), and those with 512 are even more uncommon. Could you provide examples of models that use a head dimension of 512? This would give us a stronger incentive to optimize this type of kernel.

**Comment by v4if** [comment]
> In the upcoming release, we will include kernels for head dimension of 256. However, models with a head dimension of 256 are already quite rare (only gemma-2 2b/9b as far as I know), and those with 512 are even more uncommon. Could you provide examples of models that use a head dimension of 512? This would give us a stronger incentive to optimize this type of kernel.

tks. internal model.
