### ISSUE TITLE
exist nan when using sageattn

### ISSUE THREAD

**Issue by Pydataman** [thu-ml/SageAttention#19]
use F.scaled_dot_product_attention is normal。
use sageattn，nan when llm predicted

GPU：A800

**Comment by jt-zhang** [comment]
Thank you for reaching out.
Please first check the `dtype` and `shape of q, k, v`.

**Comment by Pydataman** [comment]
> Thank you for reaching out. Please first check the `dtype` and `shape of q, k, v`.

use kv cache。
q shape：[1, 16, 1, 64]
k shape：[1, 16, xxx, 64]
v shape：[1, 16, xxx, 64]

**Comment by jt-zhang** [comment]
Thank you for reaching out.
Sorry, currently, SageAttention only support for `seq_len>128`. We have added an assertion for this.

**Comment by Pydataman** [comment]
> Thank you for reaching out. Sorry, currently, SageAttention only support for `seq_len>128`. We have added an assertion for this.

thanks！
when will it be supported for seq_len<128?

**Comment by blepping** [comment]
> We have added an assertion for this.

assertions only have an effect when Python isn't running in optimized mode (`python -O`). if you want to preserve invariants it's better to use something like an `if` + explicit `raise`.

**Comment by jt-zhang** [comment]
This issue has been addressed if you use the latest codes in our repository.
