### ISSUE TITLE
Can SageAttention available on AMD GPUs?

### ISSUE THREAD

**Issue by guanchenl** [thu-ml/SageAttention#20]
Great Work!

Can SageAttention available on AMD GPUs?

Best

**Comment by jt-zhang** [comment]
Thank you for reaching out.
In theory, as long as the Linux system can run because triton is compatible with AMD GPUs (ROCm 5.2+), but we have not tested and optimized for AMD GPUs.

**Comment by FeepingCreature** [comment]
Well, currently it complains about the lack of `nvcc`.

**Comment by markg85** [comment]
> Well, currently it complains about the lack of nvcc. Which, yeah.

You probably want [hipcc](https://github.com/ROCm/llvm-project) on the AMD side. No clue of that's going to make it work though. This would probably be just one next step towards trying an AMD compile before you run into another nvidia/cuda specific error
