### ISSUE TITLE
Real accelerated benefits

### ISSUE THREAD

**Issue by lswzjuer** [thu-ml/SageAttention#22]
Actual tests found that there was no acceleration benefit on A100 and A10 series graphics cards. Are you involved in false advertising?

**Comment by MeJerry215** [comment]
The paper say only has benefits in PTX 4096 and PTX 3090. I also try in the A10 series graphics cards, no acceleration benefit.

**Comment by jason-huang03** [comment]
The paper is focued on 4090 and 3090, whose tensor core/cuda core throughput is different from that of A100 and A10.
