### ISSUE TITLE
all black video are generated for Open-Sora-Plan using sageattention

### ISSUE THREAD

**Issue by littletomatodonkey** [thu-ml/SageAttention#23]
Hi, when i infer open-sora-plan model with sageattention, the results are all black. Do you have any idea? Thanks!

* inference scripts: https://github.com/NUS-HPC-AI-Lab/VideoSys/blob/master/examples/open_sora_plan/sample.py
* device: 4 x A100
* fsdp: 1.23s/iter
* sageattention: 1.53s/iter

**Comment by jt-zhang** [comment]
Thank you for reaching out.
Currently, SageAttention supports `headdim in [64,96,128]` while opensora is `headdim=72`. We have added an assertion for this.

For a suggestion, you could padding `headdim=72` to `headdim=128` with 0. Then, you can get a lossless video.

**Comment by jt-zhang** [comment]
What's more, sageattention has not been optimized for A100. This update will be available soon.

**Comment by asahni04** [comment]
> What's more, sageattention has not been optimized for A100. This update will be available soon.

hi @jt-zhang any updates on this? a100 is crucial

**Comment by asahni04** [comment]
> What's more, sageattention has not been optimized for A100. This update will be available soon.

hi @jt-zhang @jason-huang03  please update on this we are eagerly awaiting

**Comment by jason-huang03** [comment]
Hi, A100 does not have fp8 tensor core, making it hard to quantize PV. We will soon release the optimized kernel for Hopper (H100, H20), that matches the speed of flashattention3-fp8 but with much higher accuracy.
