### ISSUE TITLE
Q matrix quantization

### ISSUE THREAD

**Issue by liangan1** [thu-ml/SageAttention#27]
https://github.com/thu-ml/SageAttention/blob/fabd1bf77507af6afb790d0248b3dd3fad0348c7/sageattention/quant_per_block.py#L17-L21
Why need to pre and post-proess around the x/scale, is there any details about this part? I can't find the reference in the paper.

**Comment by jt-zhang** [comment]
Thank you for reaching out.
This corresponds to the fusion of $1/\sqrt{d}$ in attention to quantization. Please refer to Section 4.6 in our paper for more details.
