### ISSUE TITLE
compatible with other quantization methos

### ISSUE THREAD

**Issue by chenchunhui97** [thu-ml/SageAttention#28]
As described in the research paper, sage attention is quantize QKV to be dtype of INT8 and conduct gemm in INT8 (with accumulator of dtype float16), so I want to know is it conflict or replicated with other quantization method, such as AWQ, SmoothQuant, INT8 in vllm?

**Comment by chenchunhui97** [comment]
can this method be applied to Qwen2? not Qwen2-VL or Qwen-MOE, as I donot found Qwen2 use this func: F.scaled_dot_product_attn

**Comment by jason-huang03** [comment]
AWQ is a method for weight only quantization. However, in attention operator there is no concept of "weight". For smoothquant, there is indeed method called "SmoothAttention" which is proposed in (Qserve)[https://arxiv.org/abs/2405.04532]. Our method can definitely be used in Qwen2. The `F.scaled_dot_product_attn` appears (here)[https://github.com/huggingface/transformers/blob/main/src/transformers/models/qwen2/modeling_qwen2.py#L544].
