### ISSUE TITLE
关于SageAttention 性能为什么在RTX 4090 和 RTX 3090有明显效果

### ISSUE THREAD

**Issue by MeJerry215** [thu-ml/SageAttention#29]
论文提出两个优化点 1. qk 量化 2. fp16 累加器

Attention 本身呈现出一定的 memory-bound 和compute-bound性，当 context_len 够小的时候，就是memory-bound，当context_len 较大的时候呈现出compute-bound性质。

所以针对上面这一点 qk  int8 量化性能收益 如果按照compute-bound计算 在 (1 + 1) / (0.5 + 1) = 1.33 左右，如果按照memory-bound计算 则 (1 + 1 + 1) / (1 + 1) = 1.5 左右，非严谨计算方式。这是性能收益的部分来源，**也是int8 量化带来的收益，这一点如果使用 FP8应该也是能够达到的，且要context_len 足够大**。

对于 第二点优化 fp16 累加器的使用，由于 RTX 4090 和 RTX 3090 属于Ada 架构，而在Amphere 架构上 A10和A100 看不到加速效果，这是属于架构特性。

查看架构白皮书可以得知

Ada Architechture: https://images.nvidia.com/aem-dam/Solutions/Data-Center/l4/nvidia-ada-gpu-architecture-whitepaper-v2.1.pdf
Amphere Archtechture:  https://images.nvidia.com/aem-dam/en-zz/Solutions/data-center/nvidia-ampere-architecture-whitepaper.pdf

Ada 架构 Accumulate 算力 FP16 是FP32 的两倍，而在Amphere 架构上FP32 Accumulate 和FP16 Accumulate 算力是一致的。所以这一部分的加速效果主要**来源于硬件架构**。

如果在Ada 架构上将tl.dot output_type 修正为 tl.float32 则可以明显的观察到**加速效果降低**。

对Op 进行 profile 后可以得到如下数据，和预期分析较为吻合。

RTX 4090 和 A10 性能数据对比，可以看到即使A10 上使用 FP16 累加器，性能上相比 FP32 也**没有差异**的。
![image](https://github.com/user-attachments/assets/4c2ce91a-578a-4113-bc9d-547fe2c4428d)

同时单独列出A100性能数据， A100 可能由于算力强，所以应该没有达到 context_len 的compute bound阈值，不过也可以看到存在趋势，这里就不补充测试了

![image](https://github.com/user-attachments/assets/d34b06c6-2aa0-43a2-95b4-e01974326a49)

总结算力越强的机器，越难以达到compute-bound，加速效果应用场景越难达到。而context_len 过短，反而容易memory bound + dynamic quant overhead，也达不到预期收益。

F/G 为F列 除 G列得到的 百分比，时间单位为torch event warm 10 run 100 得到的平均值时间，单位为ms

**Comment by jason-huang03** [comment]
同意你的说法，当 context_len 够小的时候，就是memory-bound，当context_len 较大的时候呈现出compute-bound性质。在 context len 短的时候或decode的时候我们可以直接使用 flash-attention2。但”总结算力越强的机器，越难以达到compute-bound，加速效果应用场景越难达到”这句话我不是很认可。我认为应当是算力强的机器tensor core的吞吐不同，才导致最大加速比不同。
