### ISSUE TITLE
Are you planning to provide a varlen and bnsd API?

### ISSUE THREAD

**Issue by tlogn** [thu-ml/SageAttention#31]
Appreciate for your great job! Currently, the input must be bnsd(bs, head_num, seqlen, head_dim). Are you planning to offer a bsnd format and varlen API similar to flash_attn?

**Comment by jt-zhang** [comment]
Yes! This option will be available soon (less than about a week).

**Comment by jason-huang03** [comment]
#33

**Comment by tlogn** [comment]
Thans for your reply!
@jason-huang03 
Would you supply a varlen version like [this](https://github.com/vllm-project/vllm/blob/f0f2e5638ef4858b00b137bea1c3f8312e48efa6/vllm/attention/ops/triton_flash_attention.py#L309)?

**Comment by jason-huang03** [comment]
@tlogn We will try to support this feature soon.

**Comment by jason-huang03** [comment]
@tlogn varlen api is supported in #36 . We have conducted test outselves. Still we would be very thankful if you can also test its correctness.

**Comment by tlogn** [comment]
@jason-huang03 
Hi, I've checked varlen with unittest and Integrated it with mochi. Everything works well.
And I have another issue. Could you abstract a function to register kernel tiles, making it easier for users to adjust kernel on their own GPU ?

**Comment by jason-huang03** [comment]
@tlogn 
What do you mean by a function to register kernel tile? Or do you have any example code for reference? By the way, we are interested mochi too, would it be possible for us to learn how you run mochi in detail? You can reach me out with email of wechat.

**Comment by tlogn** [comment]
@jason-huang03 
I've send an email, please reply if you're interested.
