### ISSUE TITLE
How can I make it work on Windows?

### ISSUE THREAD

**Issue by jpgallegoar** [thu-ml/SageAttention#4]
I'm having lots of trouble making it work on Windows, especially because of Triton. Is it even possible?

**Comment by jt-zhang** [comment]
Thank you for reaching out!

Install torch 2.4.0 with `pip install torch==2.4.0`, which automatically installs `triton 3.0.0` as well. Alternatively, you can further `pip uninstall triton` and install triton-nightly using:

`pip install -U --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly`

**Comment by Orenji-Tangerine** [comment]
Does it work for Pytorch 2.1.2 in Windows?

**Comment by jt-zhang** [comment]
Torch 2.1.2 is compatible and should work fine, although it may not guarantee optimal kernel performance. SageAttention is OS-agnostic, so it should operate correctly on both Windows and Linux systems.

**Comment by SoftologyPro** [comment]
Trying under Windows here (adding to CogVideoX as per your demo script).

```
  File "D:\CogVideoX\CogVideo\venv\lib\site-packages\triton\runtime\build.py", line 52, in _build
    raise RuntimeError("Failed to find C compiler. Please specify via CC environment variable.")
RuntimeError: Failed to find C compiler. Please specify via CC environment variable.
```

For both Triton 2.1.0 and/or Triton 3.0.0.
Any idea what the CC env var should be set to?

**Comment by KLL535** [comment]
But don't you need to rewrite half of the file setup, for example the compilation keys, are they compatible with MSVC?

`CXX_FLAGS = ["-g", "-O3", "-fopenmp", "-lgomp", "-std=c++17", "-DENABLE_BF16"]`

Library names are all different, for exmple vcomp.lib vs omp.lib. 

I'm trying to install v2 but I can't do it.
This library _fused, it doesn't work:

```
  File "H:\ComfyUI128\python_embeded\temp\SageAttention\sageattention\quant.py", line 20, in <module>
    from . import _fused
ImportError: DLL load failed while importing _fused
```
