### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Maritime-Moon** [thu-ml/SageAttention#42]
Traceback (most recent call last):
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\graduation\CMMP\upt_tip_cache_model_free_finetune_distill3.py", line 1411, in get_origin_text_emb
    origin_text_embedding = clip_model.encode_text(text_inputs)
  File "D:\graduation\CMMP\CLIP_models_adapter_prior2.py", line 886, in encode_text
    x = self.transformer(x)
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\graduation\CMMP\CLIP_models_adapter_prior2.py", line 468, in forward
    return self.resblocks((x,prior))[0]
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\graduation\CMMP\CLIP_models_adapter_prior2.py", line 456, in forward
    x = x + self.attention(self.ln_1(x))  
  File "D:\graduation\CMMP\CLIP_models_adapter_prior2.py", line 444, in attention
    return self.attn(x, x, x, need_weights=False, attn_mask=self.attn_mask)[0]
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\nn\modules\activation.py", line 1266, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\torch\nn\functional.py", line 5504, in multi_head_attention_forward
    attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
  File "D:\anaconda3\envs\HOI_sage\lib\site-packages\sageattention\core.py", line 24, in sageattn
    assert q.size(-2)>=128, "seq_len should be not less than 128."
AssertionError: seq_len should be not less than 128.
input size is (77, 117,512),should i fix the code

**Comment by jason-huang03** [comment]
Hi, input qkv should be either in float16 or bfloat16 data format.

**Comment by jason-huang03** [comment]
Hi, the latest code remove this assertion. Also, I see that your input size is (77, 117, 512). What is your sequence length and head dim?

**Comment by Maritime-Moon** [comment]
sequence length and head dim is 77 and 64

**Comment by jason-huang03** [comment]
hi, this is supposed to work on the latest code. Note that you need to arrange the input as (batch_size, num_heads, seq_len, head_dim) or (batch_size, seq_len, num_heads, head_dim) (setting tensor_layout="NHD") before passing in.

**Comment by Maritime-Moon** [comment]
Are you referring to entering the attention module or entering the Transformer module?

**Comment by Maritime-Moon** [comment]
class CLIP(nn.Module):
    def __init__(self,
                 embed_dim: int,
                 # vision
                 image_resolution: int,
                 vision_layers: Union[Tuple[int, int, int, int], int],
                 vision_width: int,
                 vision_patch_size: int,
                 # text
                 context_length: int,
                 vocab_size: int,
                 transformer_width: int,
                 transformer_heads: int,
                 transformer_layers: int,
                #  use_adapter=True,
                 **kwargs,
                 ):
        super().__init__()

        self.context_length = context_length
        if isinstance(vision_layers, (tuple, list)):
            vision_heads = vision_width * 32 // 64
            self.visual = ModifiedResNet(
                layers=vision_layers,
                output_dim=embed_dim,
                heads=vision_heads,
                input_resolution=image_resolution,
                width=vision_width
            )
        else:
            vision_heads = vision_width // 64
            self.visual = VisionTransformer(
                input_resolution=image_resolution,
                patch_size=vision_patch_size,
                width=vision_width,
                layers=vision_layers,
                heads=vision_heads,
                output_dim=embed_dim,
                use_adapter=kwargs["use_adapter"],
                adapter_layers=kwargs["adapter_layers"],
                adapter_num_layers=kwargs["adapter_num_layers"],
                bottleneck=kwargs["bottleneck"],
            )

        self.transformer = Transformer(
            width=transformer_width,
            layers=transformer_layers,
            heads=transformer_heads,
            attn_mask=self.build_attention_mask(),
            adapter=kwargs["use_text_adapter"],
            adapter_layers=kwargs["adapter_layers"],
            adapter_num_layers=kwargs["adapter_num_layers"],
        )

        self.num_heads = transformer_heads
        self.head_dim = transformer_width // transformer_heads

        self.vocab_size = vocab_size
        self.token_embedding = nn.Embedding(vocab_size, transformer_width)
        self.positional_embedding = nn.Parameter(torch.empty(self.context_length, transformer_width))
        self.ln_final = LayerNorm(transformer_width)

        self.text_projection = nn.Parameter(torch.empty(transformer_width, embed_dim))
        self.logit_scale = nn.Parameter(torch.ones([]) * np.log(1 / 0.07))

        self.initialize_parameters()

    def initialize_parameters(self):
        nn.init.normal_(self.token_embedding.weight, std=0.02)
        nn.init.normal_(self.positional_embedding, std=0.01)

        if isinstance(self.visual, ModifiedResNet):
            if self.visual.attnpool is not None:
                std = self.visual.attnpool.c_proj.in_features ** -0.5
                nn.init.normal_(self.visual.attnpool.q_proj.weight, std=std)
                nn.init.normal_(self.visual.attnpool.k_proj.weight, std=std)
                nn.init.normal_(self.visual.attnpool.v_proj.weight, std=std)
                nn.init.normal_(self.visual.attnpool.c_proj.weight, std=std)

            for resnet_block in [self.visual.layer1, self.visual.layer2, self.visual.layer3, self.visual.layer4]:
                for name, param in resnet_block.named_parameters():
                    if name.endswith("bn3.weight"):
                        nn.init.zeros_(param)

        proj_std = (self.transformer.width ** -0.5) * ((2 * self.transformer.layers) ** -0.5)
        attn_std = self.transformer.width ** -0.5
        fc_std = (2 * self.transformer.width) ** -0.5
        for block in self.transformer.resblocks:
            nn.init.normal_(block.attn.in_proj_weight, std=attn_std)
            nn.init.normal_(block.attn.out_proj.weight, std=proj_std)
            nn.init.normal_(block.mlp.c_fc.weight, std=fc_std)
            nn.init.normal_(block.mlp.c_proj.weight, std=proj_std)

        if self.text_projection is not None:
            nn.init.normal_(self.text_projection, std=self.transformer.width ** -0.5)

    def build_attention_mask(self):
        # lazily create causal attention mask, with full attention between the vision tokens
        # pytorch uses additive attention mask; fill with -inf
        mask = torch.empty(self.context_length, self.context_length)
        mask.fill_(float("-inf"))
        mask.triu_(1)  # zero out the lower diagonal
        return mask    
    def encode_text(self, text):
        x = self.token_embedding(text).type(self.dtype)  # [batch_size, n_ctx, d_model]

        x = x + self.positional_embedding.type(self.dtype)
        x = x.permute(1, 0, 2)  # NLD -> LND
        x = self.transformer(x)                     #Enter here to report an error
        x = x.permute(1, 0, 2)  # LND -> NLD
        x = self.ln_final(x).type(self.dtype)

        # x.shape = [batch_size, n_ctx, transformer.width]
        # take features from the eot embedding (eot_token is the highest number in each sequence)
        x = x[torch.arange(x.shape[0]), text.argmax(dim=-1)] @ self.text_projectio

**Comment by Maritime-Moon** [comment]
Enter encode_text(self, text) report error

**Comment by Maritime-Moon** [comment]
How should I change it so that it can run smoothly

**Comment by jt-zhang** [comment]
Hi, please install the latest sageattention using `pip install sageattention==1.0.6`.

Then I suggest that you should ensure the input shapes of `q, k, v` are `(batch_size, num_heads, seq_len, head_dim)`, by `torch.transpose` or `torch.permute` and `torch.view` or `torch.reshape` etc.

Or you can also change the input shapes of `q, k, v` to `(batch_size, seq_len, num_heads, head_dim)`, but you need to pass `tensor_layout="NHD"` in the `sageattn` API.

**Comment by Maritime-Moon** [comment]
self.attn = nn.MultiheadAttention(d_model, n_head)
I'm using this attention block, I don't know if yours applies to it or not, and the following error appears when it is done in the run：
AssertionError: query should be unbatched 2D or batched 3D tensor but received 4-D query tensor

**Comment by Maritime-Moon** [comment]
When I was using version 2.1.1, I got the error: ImportError: DLL load failed while importing _fused: The specified program could not be found

**Comment by Maritime-Moon** [comment]
When using version 1.0.6, I get assert headim in [64, 96, 128]. afterwards， When I was using version 2.1.1, I got the error: ImportError: DLL load failed while importing _fused: The specified program could not be found

**Comment by jt-zhang** [comment]
Please see #123

**Comment by Maritime-Moon** [comment]
assert dtype in [torch.float16, torch.bfloat16],Is there no torch.float32 in version 2.1.1
