### ISSUE TITLE
Only `head_dim==128` and `headdim==64` are supported?

### ISSUE THREAD

**Issue by xmfbit** [thu-ml/SageAttention#47]
Hi, impressive work!

I find that in the CUDA implementation, here coms the assertion:

```
#define DISPATCH_HEAD_DIM(head_dim, HEAD_DIM, ...)              \
  if (head_dim == 64) {                                         \
    constexpr int HEAD_DIM = 64;                                \
    __VA_ARGS__                                                 \
  } else if (head_dim == 128) {                                 \
    constexpr int HEAD_DIM = 128;                               \
    __VA_ARGS__                                                 \
  } else {                                                      \
    std::ostringstream err_msg;                                 \
    err_msg << "Unsupported head dim: " << int(head_dim);       \
    throw std::invalid_argument(err_msg.str());                 \
  }
```

Just want to make sure that SageAttention 2.0 currently only support `head_dim==128` and `headdim==64`, right?

Thanks!

**Comment by jason-huang03** [comment]
Yes, there are difficulities to optmize performance other than 64 and 128. For other head dim, we plan to pad it to 64, 128 and 256, just as flash attention does.

**Comment by jason-huang03** [comment]
The memory accessing and tensor core computation pattern makes them most suitable for head dim that is a power of 2.

**Comment by xmfbit** [comment]
Got it! Thanks! Hope it goes well!

**Comment by Heliumrich** [comment]
Ideogram 4.0 use 256 head_dim, and so Sage Attention 2++ doesn't work :/
