### ISSUE TITLE
 speed issue compared with sdpa, fa1

### ISSUE THREAD

**Issue by 2877992943** [thu-ml/SageAttention#48]
hi, great job! I have try benchmark code on sageattention/bench files, and is faster than FA2. However when test on qwen2-1.5b generating task, the tps(token per sec) for sageattention is 43, less than that of FA2 51 . 

i have make sure that q,k,v is torch.bfloat16, and use `F.scaled_dot_product_attention = sageattn`

here is code and result

```
def run5():
    from transformers import AutoModelForCausalLM, AutoTokenizer
    device = "cuda" # the device to load the model onto

    model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2-1.5B-Instruct",
    torch_dtype="auto",
    device_map="auto"
        )
    tokenizer = AutoTokenizer.from_pretrained(
        "Qwen/Qwen2-1.5B-Instruct"
    )

    prompt = "Give me a short introduction to large language model."
    messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
    ]
    text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
    )
    model_inputs = tokenizer([text], return_tensors="pt").to(device)


    t1=time.time()
    generated_ids = model.generate(
    model_inputs.input_ids,
    max_new_tokens=512
    )
    t=time.time()-t1
    print('time delta',t)
    generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]
    print('new tokenshape',generated_ids[0].shape[0],'newtoken/time',generated_ids[0].shape[0]/t)
  
    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
  
```

here is result for sageattntion
> time delta 1.8940763473510742
 new tokenshape 82 newtoken/time 43.29286943194217
time delta 2.201706647872925
 new tokenshape 96 newtoken/time 43.60253900888471

here is  result for fa2

> time delta 2.045978546142578
new tokenshape 105 newtoken/time 51.320186224808474
time delta 3.224583148956299
 new tokenshape 165 newtoken/time 51.169404657282776

 can you provide any help for generating task

**Comment by jason-huang03** [comment]
hi, the performance boost only apply to the prefill/context stage of attention operation. For decode stage, the workload is entirely different and is out of the scope of sage attention. 

Specifically, sage attention uses int8 QK and optionally fp8 PV to utilize low bit tensor core, achieving speedup in prefill stage, which is compute bound. For decode stage which is memory bound, normally people quantize K, V to low bit and leave Q in fp16/bf16 so that the memory fetching is reduced.

In LLM generation, sage attention is extremely suitable to reduce the **time to first token** under long context scenerio. As for decode, sage attention will not bring great help. I suggest you refer to work like [Atom](https://arxiv.org/abs/2310.19102), [KIVI](https://arxiv.org/abs/2402.02750) etc that enhance decode throughput.

**Comment by Andy0422** [comment]
@jason-huang03 
Hi, I just confused what is the batch size of the kernel speed results at A100? Many thanks.

**Comment by jason-huang03** [comment]
@Andy0422 we use batch size of 4

**Comment by KLL535** [comment]
Does anyone have a simple example of how to attach this library to an LLM model, for example QWEN? It doesn't work that easy:

```
quantization_config = BitsAndBytesConfig(
                load_in_8bit=True, 
                llm_int8_threshold=6.0, 
            )
model = AutoModelForCausalLM.from_pretrained(
                model_path,
                device_map="auto",
                quantization_config=quantization_config,  
                attn_implementation="sageattn", #"sdpa"
                offload_folder="offload"  
            ).eval()
```

`Specified `attn_implementation="sageattn"` is not supported. The only possible arguments are `attn_implementation="eager"` (manual attention implementation), `"attn_implementation=flash_attention_2"` (implementation using flash attention 2), `"attn_implementation=sdpa"` (implementation using torch.nn.functional.scaled_dot_product_attention), `"attn_implementation=flex_attention"` (implementation using torch's flex_attention).`
