### ISSUE TITLE
How to fairely compare fa2 vs sageattention？

### ISSUE THREAD

**Issue by zhangxin81** [thu-ml/SageAttention#57]
Baseline: fa2
batch: 4, head: 32, headdim: 128
is_causal: True
1024 flops:120.25234943319238
2048 flops:147.6664744959366
4096 flops:174.18947358803356
8192 flops:192.45342302595006
16384 flops:199.40070470077464
32768 flops:199.20074507503034
begin to test flash
1024 flops:221.6447050332628
2048 flops:469.19870304601994
4096 flops:804.7877869549036
8192 flops:1631.8505044002102
16384 flops:3859.924676064202
32768 flops:7746.594285762916
As above shown，my test result show that sageattention is slower than fa2，I wander how to write correct config to compare?

code for fa2:
print(f"begin to test flash")
for seq_len in {1024, 2048, 4096, 8192, 16384, 32768}:
    flops = 4 * head * batch * headdim * seq_len * seq_len // (2 if is_causal else 1)
    q = torch.randn(batch, head, seq_len, headdim).half().cuda()
    k = torch.randn(batch, head, seq_len, headdim).half().cuda()
    v = torch.randn(batch, head, seq_len, headdim).half().cuda()
    for i in range(5): sdpa(q, k, v, is_causal=is_causal)
    torch.cuda.synchronize()
    #_, time = benchmark_forward(sdpa, q, k, v, is_causal=is_causal, repeats=100, verbose=False, desc='Triton')
    _, time = benchmark_forward(flash_attn_func, q, k, v, 0.0, causal=True, repeats=100, verbose=False)
    print(f'{seq_len} flops:{flops/time.mean*1e-12}')

P.S.
Our Nvidia Environment:
A800
python: 3.10
torch: 2.4.0a0+07cecf4
flash-attn: 2.7.0.post2
sageAttention: 2.0.0

Thanks a lot!

**Comment by jason-huang03** [comment]
hi, your code for testing fa2 is incorrect. As you can see, the throughput rise to a few thousands which is not possible. The problem is that the tensor you pass to `flash_attn_func` is of wrong layout. You need to pass q, k, v of shape `[batch_size, seq_len, num_heads, head_dim]' to fa2.
