### ISSUE TITLE
Support for flux?

### ISSUE THREAD

**Issue by ali-afridi26** [thu-ml/SageAttention#58]
I am trying to test sage attention for Flux Schnell. I am getting this error: 
`-> assert head_dim in [64, 128], "sageattn_qk_int8_pv_fp16_cuda only support head_dim [64, 128]."`

**Comment by jt-zhang** [comment]
Hi, could you provide more information about how you replace the attention in Flux.
I think the `headdim` in Flux is 64. Maybe you should only replace the attention in `model.transformer_blocks` and `model.single_transformer_blocks`

**Comment by ali-afridi26** [comment]
I used this:
```
torch.nn.functional.scaled_dot_product_attention = sageattn
pipe = FluxPipeline.from_pretrained("black-forest-labs/FLUX.1-schnell", torch_dtype=torch.bfloat16).to("cuda")

pipe.vae.enable_slicing()
pipe.vae.enable_tiling()

prompt = "A cat holding a sign that says hello world"
start = time.time()
image = pipe(
    prompt=prompt,
    guidance_scale=0.,
    height=768,
    width=1360,
    num_inference_steps=4,
    max_sequence_length=256,
    generator=torch.Generator("cuda").manual_seed(0)
).images[0]
print("sage attn timing = ",time.time()-start)
image.save(f"ali.png")
```

**Comment by jt-zhang** [comment]
You can try to replace the attention function in `FluxTransformer2DModel.transformer_blocks.attn` by modify the source code of diffusers.
