### ISSUE TITLE
After update diffusers CogVideoX fails due to the dtype check

### ISSUE THREAD

**Issue by kijai** [thu-ml/SageAttention#6]
Hey, great work on this, speeded things up a lot!

I'm having this issue after the 1.0.0 update:
In the diffusers CogVideoX code, the q and k dtypes seem to be fp32, so the dtype check in [core.py](https://github.com/thu-ml/SageAttention/blob/486da2407603463eb851464cc60142f7ae59d181/sageattention/core.py#L28) will always fail with error:

`local variable 'o' referenced before assignment`

If I change it to check the v.dtype it works, with the model being loaded in fp16 or bf16. What would be the best way to handle this?

**Comment by jt-zhang** [comment]
Thank you for reaching out. 
Currently, `sageattn` can only receive `q, k, v` in FP16/BF16. 
Maybe you can try to convert the `q, k, v` to FP16/BF16 before calling `sageattn`, or you can try the Cogvideo codes in `./example` in our repository.

**Comment by kijai** [comment]
It still seems to be working as long as the v is fp/bf16 though? And it worked fine before this update as well in this same code. If I check dtype of q, k, v before the function call they are fp32/fp32/bf or fp16.

**Comment by jt-zhang** [comment]
Thank you for your advice.
We have updated the source code. Now you can use `pip install sageattention==1.0.2 -i https://pypi.org/simple/` to reinstall `sageattention`. This version will automatically convert fp32 to fp16/bf16.
