### ISSUE TITLE
 sageattn_qk_int8_pv_fp16_cuda only support head_dim [64, 128]

### ISSUE THREAD

**Issue by wangshankun** [thu-ml/SageAttention#62]
SageAttention/sageattention/core.py", line 590, in sageattn_qk_int8_pv_fp8_cuda
    assert head_dim in [64, 128], "sageattn_qk_int8_pv_fp16_cuda only support head_dim [64, 128]."

是只能支持head_dim是64和128的attn吗？

**Comment by jt-zhang** [comment]
Thank you for reaching out.
Yes, 64 and 128 are the most commonly used `headdim`; you can use padding and change the `sm_scale` to support other headdim that < 128.
Also, the triton backend supports `headdim=96`.

**Comment by jason-huang03** [comment]
Please see #47
