### ISSUE TITLE
Regarding the issue of installing the 2.0.0 source code

### ISSUE THREAD

**Issue by MikeAiJF** [thu-ml/SageAttention#67]
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///project_01/ComfyUI/SageAttention-2.0.0
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/project_01/ComfyUI/SageAttention-2.0.0/setup.py", line 116, in <module>
          raise RuntimeError("CUDA 12.0 or higher is required to build the package.")
      RuntimeError: CUDA 12.0 or higher is required to build the package.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by protector131090** [comment]
pip uninstall torch
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
