### ISSUE TITLE
How much time will we save if we use sageattn_cogvideo.py instead of original_cogvideo.py

### ISSUE THREAD

**Issue by rxmao** [thu-ml/SageAttention#68]
Thank you!

**Comment by jt-zhang** [comment]
In cogvideoX-2B (SAT), it is about 34%. We are testing the speedup in other cogvideo models.

**Comment by bm-synth** [comment]
> In cogvideoX-2B (SAT), it is about 34%. We are testing the speedup in other cogvideo models.

@jt-zhang  as a side note, could these 34% speedup be due to the `original_cogvideo.py` file missing the `.to("cuda")` instruction that moves the pipeline to the GPU?

ie in `original_cogvideo.py`:
```
pipe = CogVideoXPipeline.from_pretrained(
    "THUDM/CogVideoX-2b",
    torch_dtype=torch.float16
) 
```

vs `sage_cogvideo.py`:

```
pipe = CogVideoXPipeline.from_pretrained(
    "THUDM/CogVideoX-2b",
    torch_dtype=torch.float16
).to("cuda")    ##### this bit missing in original_cogvideo.py
```

**Comment by jt-zhang** [comment]
I do not think the `.to("cuda")` will affect the speedup effect. Maybe you can have a try.
Also, the `SAT` example corresponds to the second example in ./example/README.md.
