### ISSUE TITLE
Poor performance on L40S, no `int4`.

### ISSUE THREAD

**Issue by bm-synth** [thu-ml/SageAttention#69]
Im struggling to achieve a speedup with the latest SageAttention2.

Run environment:
- python 3.11
- pytorch 2.5.1+cu124
- GPU: NVIDIA L40S
- CUDA version 12.4
- GPU Driver Version: 550.90.07

I ran the following test script to benchmark several implementations of attention.
```python
from __future__ import annotations

import time

import sageattention as sa
import torch
from flash_attn import flash_attn_func as flash_attn_2
from torch.nn.functional import scaled_dot_product_attention

if __name__ == '__main__':

    shape = (1, 9676, 48, 64)  # B, N, H, D
    iterations = 500
    q = k = v = torch.randn(shape, dtype=torch.bfloat16, device='cuda:0')  # B, N, H, D aka NHD
    q2 = k2 = v2 = q.transpose(1, 2).clone()  # B, H, N, D aka HND

    run_cmds = {
        "torch.nn.scaled_dot_product_attention": lambda: scaled_dot_product_attention(q2, k2, v2, is_causal=False),
        "flash_attn_2": lambda: flash_attn_2(q, k, v, causal=False),
        "sageattn_qk_int8_pv_fp16_triton_NHD": lambda: sa.sageattn_qk_int8_pv_fp16_triton(
            q, k, v,
            tensor_layout="NHD",
            is_causal=False
        ),
        "sageattn_qk_int8_pv_fp16_triton_HND": lambda: sa.sageattn_qk_int8_pv_fp16_triton(
            q2, k2, v2,
            tensor_layout="HND",
            is_causal=False
        ),
        "sageattn_qk_int8_pv_fp16_cuda_NHD": lambda: sa.sageattn_qk_int8_pv_fp16_cuda(
            q, k, v,
            tensor_layout="NHD",
            is_causal=False
        ),
        "sageattn_qk_int8_pv_fp16_cuda_HND": lambda: sa.sageattn_qk_int8_pv_fp16_cuda(
            q2, k2, v2,
            tensor_layout="HND",
            is_causal=False
        ),
        "sageattn_qk_int8_pv_fp8_cuda_NHD": lambda: sa.sageattn_qk_int8_pv_fp8_cuda(
            q, k, v,
            tensor_layout="NHD",
            is_causal=False
        ),
        "sageattn_qk_int8_pv_fp8_cuda_HND": lambda: sa.sageattn_qk_int8_pv_fp8_cuda(
            q2, k2, v2,
            tensor_layout="HND",
            is_causal=False
        ),
    }

    # run few warmup iterations, and few benchmark iterations
    print(f"Input shape: {shape}, dtype: {q.dtype}, device: {q.device}, iterations: {iterations}")
    for name, fn in run_cmds.items():
        for _ in range(iterations):
            fn()
        start_time = time.time()
        for _ in range(iterations):
            fn()
        print(f"{name}: {time.time() - start_time} secs")
```

For the following input
```
shape: (1, 9676, 48, 64), dtype: torch.bfloat16, device: cuda:0, iterations: 100
```
The benchmark output was the following:
```
torch.nn.scaled_dot_product_attention: 0.0077440738677978516 secs
flash_attn_2: 2.976247549057007 secs
sageattn_qk_int8_pv_fp16_triton_NHD: 2.6961278915405273 secs
sageattn_qk_int8_pv_fp16_triton_HND: 2.641960382461548 secs
sageattn_qk_int8_pv_fp16_cuda_NHD: 2.4095118045806885 secs
sageattn_qk_int8_pv_fp16_cuda_HND: 2.308112859725952 secs
sageattn_qk_int8_pv_fp8_cuda_NHD: 1.932861089706421 secs
sageattn_qk_int8_pv_fp8_cuda_HND: 1.8761472702026367 secs
```

Changing datatype to `float16` (instead of `bfloat16`):

```
torch.nn.scaled_dot_product_attention: 0.006928443908691406 secs
flash_attn_2: 0.04552483558654785 secs
sageattn_qk_int8_pv_fp16_triton_NHD: 2.703495979309082 secs
sageattn_qk_int8_pv_fp16_triton_HND: 2.6662003993988037 secs
sageattn_qk_int8_pv_fp16_cuda_NHD: 2.5150742530822754 secs
sageattn_qk_int8_pv_fp16_cuda_HND: 2.452512741088867 secs
sageattn_qk_int8_pv_fp8_cuda_NHD: 1.9942076206207275 secs
sageattn_qk_int8_pv_fp8_cuda_HND: 1.9415948390960693 secs
```

On top of that:
- increasing sequence length to 20k and head count to 64 made no difference on the conclusions;
- the examples in [sageattn_cogvideo.py](https://github.com/thu-ml/SageAttention/blob/main/example/sageattn_cogvideo.py) and [original_cogvideo.py](https://github.com/thu-ml/SageAttention/blob/main/example/original_cogvideo.py) take the same time per iteration, far from the [34% speed-up expected](https://github.com/thu-ml/SageAttention/issues/68#issuecomment-2535146109). Could this be a bug due to [missing the `pipe.to("cuda")` command](https://github.com/thu-ml/SageAttention/issues/68#issuecomment-2535878350) in `original_cogvideo.py` ?

Questions:
- Why is SageAttn less performant than flash attention or `torch.nn.scaled_dot_product_attention`: could it be the GPU hardware (L40s) or the torch version (2.5)?
- Are the `int4` interfaces going to be released anytime soon?

**Comment by jason-huang03** [comment]
It is really weird that SageAttention lacks behind so much (several orders of magnitude). We do not have L40s at hand. Is it possible that you can provide access to L40s so that we can investigate the reason?

**Comment by bm-synth** [comment]
> It is really weird that SageAttention lacks behind so much (several orders of magnitude). We do not have L40s at hand. Is it possible that you can provide access to L40s so that we can investigate the reason?

I cannot provide access to the machine with the L40S, but we can have a 1:1 videocall where I mount a clean docker image and replicate this behaviour on the L40S. Would this work for you?

**Comment by jt-zhang** [comment]
@bm-synth Please note that `scaled_dot_product_attention` should receive `q,k,v` in the layout of `HND` rather than `NHD`.

**Comment by bm-synth** [comment]
The issue was on the missing `torch.cuda.synchronize()` before getting the times. It is explained on detail [here](https://www.speechmatics.com/company/articles-and-news/timing-operations-in-pytorch).  Adding that line before the `time.time()` calls, the new numbers are:

```
Input shape: (1, 9676, 48, 64), dtype: torch.bfloat16, device: cuda:0, iterations: 500
torch.nn.scaled_dot_product_attention: 2.96696138381958 secs
flash_attn_2: 2.906168222427368 secs
sageattn_qk_int8_pv_fp8_cuda_NHD: 1.911001205444336 secs
sageattn_qk_int8_pv_fp8_cuda_HND: 1.8606855869293213 secs
```

So indeed, Sage Attention is faster. Thank you very much @jason-huang03 for the help.
