### ISSUE TITLE
Rename folder 'resource' in repo to avoid error when running on Windows

### ISSUE THREAD

**Issue by lyxkilo** [thu-ml/SageAttention#80]
On Windows, error "module 'resource' has no attribute 'getpagesize'" occurs when using SageAttention built from source with other project files trying to import module 'resource' and handling exceptions incorrectly (e.g. launch ComfyUI and some custom node might throw this). This issue was discussed [here](https://github.com/jupyter/notebook/issues/5817). 

Rename the folder 'resource' can solve this problem.

**Comment by jt-zhang** [comment]
Thank you for your advice! We have renamed the resource folder to assets.
